### ISSUE TITLE
启动企业微信，但是并没有出现界面

### ISSUE THREAD

**Issue by ati46** [BoringCat/docker-WXWork#1]
archlinux，使用i3窗口
下载完镜像，使用docker启动后并未出现界面，
![image](https://user-images.githubusercontent.com/33859622/79852101-ce084d00-83f8-11ea-8965-7f522ac6feff.png)

**Comment by BoringCat** [comment]
我先拉下来看看，可能是整合wine文件的时候出了问题

**Comment by BoringCat** [comment]
镜像本身经过测试是没有问题的
可能导致问题的原因如下：

- 第一次启动时等待时间太长手动Ctrl+C或其他原因，导致7z没能完全解压wine文件  
- 使用持久化后文件被其他应用清理导致wine文件缺失

解决顺序：
1. （如果有持久化(映射容器/home/wechat/.deepinwine)），备份主要文件后删除持久化文件夹
2. 使用 `docker container ls -a` 找到企业微信容器，删除容器后重新执行命令

<details>
<summary>测试日志</summary>

``` sh
docker-compose pull wxwork
Pulling wxwork ... done
docker-compose up wxwork
Creating wxwork ... done
Attaching to wxwork
wxwork       | chown: cannot access '/home/wechat/.deepinwine': 没有那个文件或目录
wxwork       | 启动 WXWork
wxwork       | Run Deepin-WXWork 2.8.10.2010deepin0 c:/Program Files/WXWork/WXWork.exe
wxwork       | run Deepin-WXWork progress pid 
wxwork       | 
wxwork       | 7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
wxwork       | p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,32 bits,4 CPUs Intel(R) Core(TM) m3-8100Y CPU @ 1.10GHz (806E9),ASM,AES-NI)
wxwork       | 
wxwork       | Scanning the drive for archives:
wxwork       | 1 file, 350102989 bytes (334 MiB)
wxwork       | 
wxwork       | Extracting archive: /opt/deepinwine/apps/Deepin-WXWork/files.7z
wxwork       | --
wxwork       | Path = /opt/deepinwine/apps/Deepin-WXWork/files.7z
wxwork       | Type = 7z
wxwork       | Physical Size = 350102989
wxwork       | Headers Size = 32553
wxwork       | Method = Delta LZMA2:24 BCJ
wxwork       | Solid = +
wxwork       | Blocks = 6
wxwork       | 
wxwork       | Everything is Ok
wxwork       | 
wxwork       | Folders: 590
wxwork       | Files: 3900
wxwork       | Size:       1089132152
wxwork       | Compressed: 350102989
wxwork       | total 12
wxwork       | lrwxrwxrwx 1 wechat wechat 10 4月  21 19:22 c: -> ../drive_c
wxwork       | lrwxrwxrwx 1 wechat wechat 12 4月  21 19:22 y: -> /home/wechat
wxwork       | lrwxrwxrwx 1 wechat wechat  1 4月  21 19:22 z: -> /
wxwork       | total 12
wxwork       | lrwxrwxrwx 1 wechat wechat 10 4月  21 19:22 c: -> ../drive_c
wxwork       | lrwxrwxrwx 1 wechat wechat 12 4月  21 19:22 y: -> /home/wechat
wxwork       | lrwxrwxrwx 1 wechat wechat  1 4月  21 19:22 z: -> /
wxwork       | CallApp Deepin-WXWork c:/Program Files/WXWork/WXWork.exe
wxwork       | 2020年 04月 21日 星期二 19:22:48 UTC:kill WXWork.exe block
wxwork       | 2020年 04月 21日 星期二 19:22:48 UTC:No wine process found
wxwork       | /home/wechat/.deepinwine/Deepin-WXWork/drive_c/Program Files/WXWork
wxwork       | Starting process c:/Program Files/WXWork/WXWork.exe ...
wxwork       | wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wxwork       | wine version: 2.18
wxwork       | Xlib:  extension "MIT-SHM" missing on display "unix:1".
wxwork       | Could not load wine-gecko. HTML rendering will be disabled.
wxwork       | wine: configuration in '/home/wechat/.deepinwine/Deepin-WXWork' has been updated.
wxwork       | Xlib:  extension "MIT-SHM" missing on display "unix:1".
wxwork       | Xlib:  extension "MIT-SHM" missing on display "unix:1".
^CGracefully stopping... (press Ctrl+C again to force)

docker image ls boringcat/wechat:work
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
boringcat/wechat    work                5e7e2e45ce3f        11 days ago         2.21GB
```

</details>

<details>
<summary>Docker-Compose配置</summary>

``` yaml
version: '2'
services:
  wxwork:
    image: boringcat/wechat:work
    container_name: wxwork
    hostname: wxwork
    devices:
      - /dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./Documents/WXWork:/WXWork
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - DISPLAY=unix$DISPLAY
      - QT_IM_MODULE=fcitx
      - XMODIFIERS=@im=fcitx
      - GTK_IM_MODULE=fcitx
      - AUDIO_GID=995
      - GID=1000
      - UID=1000
    networks: 
      - brc
```

</details>
